// onion-crawler — Step 6: Concurrent downloads & processing with Tokio
//
// Building on Step 5, the pipeline now runs concurrently:
//   - Multiple archives download in parallel (async I/O with reqwest)
//   - Parsing starts as soon as each download completes (pipeline)
//   - CPU-bound WARC parsing runs on Tokio's blocking thread pool
//
// The key insight: I/O-bound work (downloads) benefits from async because the
// thread is released during network waits. CPU-bound work (parsing) still needs
// real threads — `spawn_blocking` bridges the two worlds.
//
// New concepts: async/await, Tokio runtime, reqwest streaming, spawn_blocking,
// bounded concurrency with buffer_unordered, Arc for shared ownership.

use std::collections::HashSet;
use std::fs::{self, File};
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::process;
use std::sync::Arc;
use std::time::{Duration, Instant};

use clap::Parser;
use futures::stream::{self, StreamExt};
use regex::Regex;

use onion_crawler::{
    download_warc_async, filename_from_uri, load_processed, load_results,
    mark_processed, parse_warc, save_results, RESULTS_FILE,
};

// ---------------------------------------------------------------------------
// CLI Argument Parsing
// ---------------------------------------------------------------------------

/// Detect the number of CPU cores available for parallel work.
///
/// `available_parallelism()` queries the OS for the number of logical CPUs
/// (hardware threads). This is the right default for our workload: each job
/// does CPU-bound parsing (gzip decompression + regex) via `spawn_blocking`,
/// so one job per core avoids oversubscription. Falls back to 1 if detection
/// fails (e.g. in constrained containers).
fn default_jobs() -> usize {
    std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(1)
}

// Parsed command-line configuration.
//
// Uses `clap` derive — the idiomatic Rust way to define CLI interfaces.
// The `#[derive(Parser)]` macro generates all the argument parsing, validation,
// short flags (`-l`, `-j`, `-d`), and `--help` text from the struct definition.
// Field doc comments (`///`) become the help descriptions automatically.
// We use `//` (not `///`) for these explanatory comments so clap doesn't
// include them in the `--help` output — only `///` on fields becomes help text.
#[derive(Parser)]
#[command(name = "onion-crawler")]
#[command(about = "Extract .onion addresses from Common Crawl WARC archives")]
struct Config {
    /// Path to the WARC-paths file (supports .gz)
    input: String,

    /// Maximum number of archives to process (default: all)
    #[arg(short, long)]
    limit: Option<usize>,

    /// Number of concurrent download+parse tasks
    #[arg(short, long, default_value_t = default_jobs())]
    jobs: usize,

    /// Delete archive files after parsing
    #[arg(short, long)]
    delete: bool,
}

// ---------------------------------------------------------------------------
// Per-archive task result
// ---------------------------------------------------------------------------

/// The outcome of processing a single archive — passed back from each
/// concurrent task to the main task for merging.
///
/// We need this struct because each task runs independently and can't
/// mutate shared state. Instead, each task returns its results and the
/// main task merges them sequentially — no locks needed.
struct ArchiveResult {
    onions: HashSet<String>,
    download_time: Duration,
    parse_time: Duration
}

// ---------------------------------------------------------------------------
// Main — async entry point
// ---------------------------------------------------------------------------

/// ## `#[tokio::main]` — the async runtime entry point
///
/// Rust's `main` must be synchronous, but we need an async runtime to drive
/// our concurrent downloads. `#[tokio::main]` is a macro that:
/// 1. Creates a multi-threaded Tokio runtime (default: one thread per CPU core)
/// 2. Runs our `async fn main()` on that runtime
/// 3. Shuts down the runtime when `main` completes
///
/// This is equivalent to writing:
/// ```
/// fn main() {
///     tokio::runtime::Runtime::new().unwrap().block_on(async { ... })
/// }
/// ```
/// The macro is just more concise.
#[tokio::main]
async fn main() {
    // --- Parse CLI arguments (synchronous — runs before the async work) ---
    // `Config::parse()` is generated by the `clap` derive macro. It reads
    // `std::env::args()`, validates types, and exits with a help message
    // if required arguments are missing or `--help` is passed.
    let config = Config::parse();

    let limit_display = match config.limit {
        Some(n) => format!("{}", n),
        None => "all".to_string(),
    };
    eprintln!(
        "Reading WARC paths from '{}' (limit: {}, jobs: {}, delete after: {})",
        config.input, limit_display, config.jobs, config.delete
    );

    // --- Open and read the paths file ---
    // Supports both plain text and gzip-compressed (.gz) paths files.
    // Common Crawl distributes warc.paths.gz — we decompress transparently
    // using `libflate`, which is already in the dependency tree via the `warc` crate.
    let file = File::open(&config.input).unwrap_or_else(|err| {
        eprintln!("Error: cannot open '{}': {}", config.input, err);
        process::exit(1);
    });

    let reader: Box<dyn BufRead> = if config.input.ends_with(".gz") {
        let decoder = libflate::gzip::Decoder::new(file).unwrap_or_else(|err| {
            eprintln!(
                "Error: failed to decompress '{}': {}",
                config.input, err
            );
            process::exit(1);
        });
        Box::new(BufReader::new(decoder))
    } else {
        Box::new(BufReader::new(file))
    };

    let uris: Vec<String> = reader
        .lines()
        .filter_map(Result::ok)
        .map(|line| line.trim().to_string())
        .filter(|line| !line.is_empty())
        .collect();

    if uris.is_empty() {
        eprintln!("No paths found in '{}'", config.input);
        process::exit(1);
    }

    eprintln!("Found {} path(s) in file", uris.len());

    // --- Load persistent state ---
    let processed = load_processed();
    let mut results = load_results();

    eprintln!(
        "State: {} already processed, {} onion(s) in results\n",
        processed.len(),
        results.len()
    );

    // --- Filter URIs: skip already-processed, apply limit ---
    // We do this upfront so we know exactly which archives to process
    // concurrently. Skipped archives are logged but don't count toward
    // the limit.
    let mut work_items: Vec<(usize, String)> = Vec::new();
    let mut skip_count: usize = 0;

    for (i, uri) in uris.iter().enumerate() {
        let filename = match filename_from_uri(uri) {
            Ok(f) => f,
            Err(err) => {
                eprintln!("[{}] {}: {}", i + 1, uri, err);
                continue;
            }
        };

        if processed.contains(filename) {
            eprintln!("[{}] {} — already processed, skipping", i + 1, filename);
            skip_count += 1;
            continue;
        }

        if let Some(limit) = config.limit {
            if work_items.len() >= limit {
                eprintln!("Reached processing limit of {}. Stopping.", limit);
                break;
            }
        }

        work_items.push((i + 1, uri.clone()));
    }

    if work_items.is_empty() {
        eprintln!("No archives to process.");
        // Still save results (safety net) and print summary.
        match save_results(&results) {
            Ok(()) => eprintln!("Results saved to {}", RESULTS_FILE),
            Err(err) => eprintln!("Error saving results: {}", err),
        }
        eprintln!(
            "\nSummary: 0 processed, {} skipped, 0 failed, 0 new onion(s)",
            skip_count
        );
        eprintln!(
            "Total: {} unique .onion address(es) in results",
            results.len()
        );
        return;
    }

    eprintln!("Processing {} archive(s) with {} concurrent job(s)\n", work_items.len(), config.jobs);

    // --- Compile the .onion regex once, wrapped in Arc for sharing ---
    //
    // ## `Arc` — atomic reference counting for shared ownership
    //
    // Each concurrent task needs access to the compiled regex. We can't
    // pass a `&Regex` reference because async tasks may outlive the current
    // scope (Tokio needs `'static` lifetimes for spawned tasks).
    //
    // `Arc` (Atomic Reference Count) solves this: it's a thread-safe smart
    // pointer that keeps the inner value alive as long as any clone exists.
    // Cloning an `Arc` just increments a counter — the regex itself is
    // never copied. This is Rust's standard pattern for sharing immutable
    // data across threads.
    let onion_re = Arc::new(
        Regex::new(r"\b([a-z2-7]{16}|[a-z2-7]{56})\.onion\b")
            .expect("Invalid regex"),
    );

    // --- Create a shared HTTP client ---
    //
    // `reqwest::Client` maintains a connection pool internally. Sharing one
    // client across all tasks lets them reuse TCP connections to the same
    // server (HTTP keep-alive), which is faster than each task opening its
    // own connection.
    let client = reqwest::Client::builder()
        .connect_timeout(std::time::Duration::from_secs(30))
        .build()
        .expect("Failed to build HTTP client");

    let delete = config.delete;

    // --- Concurrent pipeline with `buffer_unordered` ---
    //
    // ## How the pipeline works
    //
    // `stream::iter(work_items)` creates a stream of (index, uri) pairs.
    // `.map(|item| async { ... })` transforms each into a future that
    // downloads + parses one archive.
    //
    // `.buffer_unordered(jobs)` is the concurrency controller:
    // - It polls up to `jobs` futures simultaneously
    // - Results are yielded as soon as any future completes (not in order)
    // - When one completes, the next pending future starts
    //
    // This gives us bounded concurrency without manual semaphore management.
    // "Unordered" means faster archives finish first — we don't block
    // waiting for a slow download just because it started earlier.
    let archive_stream = stream::iter(work_items)
        .map(|(idx, uri)| {
            // Clone shared resources for this task. `Arc::clone` is cheap
            // (just increments a reference count).
            let client = client.clone();
            let onion_re = Arc::clone(&onion_re);

            async move {
                let filename = match filename_from_uri(&uri) {
                    Ok(f) => f.to_string(),
                    Err(err) => {
                        eprintln!("[{}] {}: {}", idx, uri, err);
                        return Err(format!("{}: {}", uri, err));
                    }
                };

                eprintln!("[{}] {}", idx, filename);

                // --- Download if not already on disk ---
                let local_path: PathBuf = Path::new("download").join(&filename);
                let download_start = Instant::now();
                if !local_path.exists() {
                    match download_warc_async(&client, &uri).await {
                        Ok(_) => {}
                        Err(err) => {
                            eprintln!("  [{}] Download error: {}", filename, err);
                            return Err(format!("{}: download error: {}", filename, err));
                        }
                    }
                } else {
                    eprintln!("  [{}] Already downloaded", filename);
                }
                let download_time = download_start.elapsed();
                eprintln!("  [{}] Download time: {:.1}s", filename, download_time.as_secs_f64());

                // --- Parse on the blocking thread pool ---
                //
                // ## `spawn_blocking` — bridging sync and async
                //
                // `parse_warc` is CPU-bound (gzip decompression + regex).
                // Running it directly on an async task would block the Tokio
                // worker thread, starving other async tasks (downloads).
                //
                // `spawn_blocking` moves the work to Tokio's dedicated
                // blocking thread pool, which has many more threads and
                // expects blocking work. The `.await` here suspends the
                // async task until the blocking work finishes, freeing the
                // worker thread for other downloads.
                //
                // Rule of thumb: if a function does CPU work or calls
                // blocking I/O for more than a few microseconds, use
                // `spawn_blocking`.
                eprintln!("  [{}] Parsing...", filename);
                let parse_path = local_path.clone();
                let parse_re = Arc::clone(&onion_re);

                let parse_start = Instant::now();
                let parse_result = tokio::task::spawn_blocking(move || {
                    parse_warc(&parse_path, &parse_re)
                })
                .await;
                let parse_time = parse_start.elapsed();

                // `spawn_blocking` returns a `JoinHandle` — unwrap the
                // outer Result (task panic) then the inner Result (parse error).
                let onions = match parse_result {
                    Ok(Ok(onions)) => onions,
                    Ok(Err(err)) => {
                        eprintln!("  [{}] Parse error: {}", filename, err);
                        return Err(format!("{}: parse error: {}", filename, err));
                    }
                    Err(err) => {
                        eprintln!("  [{}] Task panic: {}", filename, err);
                        return Err(format!("{}: task panic: {}", filename, err));
                    }
                };

                eprintln!("  [{}] Parsing time: {:.1}s", filename, parse_time.as_secs_f64());
                eprintln!("  [{}] Found {} unique .onion address(es)", filename, onions.len());

                Ok((idx, filename, local_path, ArchiveResult { onions, download_time, parse_time }))
            }
        })
        .buffer_unordered(config.jobs);

    // --- Collect results back on the main task ---
    //
    // `buffer_unordered` yields results as futures complete. We process
    // them sequentially here: merge onions into the shared results map,
    // mark archives as processed, and optionally delete files.
    //
    // This is a key design choice: concurrent *work*, sequential *merging*.
    // No locks, no race conditions — the simplest correct approach.
    let mut process_count: usize = 0;
    let mut fail_count: usize = 0;
    let mut new_onions: usize = 0;
    let mut total_download = Duration::ZERO;
    let mut total_parse = Duration::ZERO;

    // `pin_mut!` pins the stream to the stack so we can poll it.
    // This is needed because `buffer_unordered` returns a stream that
    // must be pinned to be polled (a Rust async trait requirement).
    futures::pin_mut!(archive_stream);

    while let Some(task_result) = archive_stream.next().await {
        match task_result {
            Ok((_idx, filename, local_path, archive)) => {
                total_download += archive.download_time;
                total_parse += archive.parse_time;
                let count_before = results.len();
                for onion in archive.onions {
                    let archives = results.entry(onion).or_default();
                    if !archives.contains(&filename) {
                        archives.push(filename.clone());
                    }
                }
                let added = results.len() - count_before;
                new_onions += added;

                if let Err(err) = mark_processed(&filename) {
                    eprintln!("  Warning: couldn't mark as processed: {}", err);
                }
                if let Err(err) = save_results(&results) {
                    eprintln!("  Warning: couldn't save results: {}", err);
                }

                process_count += 1;

                if delete {
                    match fs::remove_file(&local_path) {
                        Ok(()) => eprintln!("  [{}] Deleted {}", filename, local_path.display()),
                        Err(err) => eprintln!("  [{}] Warning: couldn't delete: {}", filename, err),
                    }
                }

                eprintln!();
            }
            Err(err) => {
                eprintln!("  Error: {}", err);
                fail_count += 1;
                eprintln!();
            }
        }
    }

    // --- Final save (safety net) ---
    match save_results(&results) {
        Ok(()) => eprintln!("Results saved to {}", RESULTS_FILE),
        Err(err) => eprintln!("Error saving results: {}", err),
    }

    // --- Summary ---
    eprintln!(
        "\nSummary: {} processed, {} skipped, {} failed, {} new onion(s)",
        process_count, skip_count, fail_count, new_onions
    );
    eprintln!(
        "Total: {} unique .onion address(es) in results",
        results.len()
    );
    if process_count > 0 {
        let avg_dl = total_download.as_secs_f64() / process_count as f64;
        let avg_parse = total_parse.as_secs_f64() / process_count as f64;
        eprintln!(
            "Avg per archive: {:.1}s download, {:.1}s parsing",
            avg_dl, avg_parse
        );
    }
}
